config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'bios#index'
	resources :bios do
	resources :comments
end
	resources :photos
	resources :stories
end
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
	validates :name, :presence => true
	
	validates :description, :presence => true
	validates :hometown, :presence => true
	

	has_many :comments
	belongs_to :user
	has_many :photos
	mount_uploader :picture, PictureUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :user
	belongs_to :bio
	
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :bios, dependent: :destroy
   has_many :photos
   has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index
		@bios = Bio.all.paginate(page: params[:page], per_page: 2)

	end

	def new
		@bio = Bio.new
	end

	def show
		@bio = Bio.find(params[:id])
		@comment = Comment.new
	end

	def create
		@bio = Bio.find_by(params[:id])
		@bio = current_user.bios.create(bio_params)
		if @bio.save 
		 redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end


	private

	def bio_params
		params.require(:bio).permit(:name, :description, :hometown, :picture, :rating)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def index
		@comments = Comment.all
	end

	def new
		@comment = Comment.new
	end

	def create
		@bio = Bio.find(params[:bio_id])
		@bio.comments.create(comment_params.merge(user: current_user))
		if @current_user.save
			flash[:success] = "New Comment Created!"
		redirect_to bio_path(@bio)
		else
			render 'new'
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:message)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def index
		@photos = Photo.all
	end

	def create
		@bio = Bio.find(params[:bio_id])
		@bio.photos.create(bio_params)
		redirect_to bio_path(@bio)
	end

	private

	def photo_params
		params.require(:photo).permit(:picture, :caption)
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

 def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissable") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end

  def rating_star(value)
    percentage = value / 5 * 100

    fg = content_tag 'div', class: 'rating-star-value', style: "width: #{percentage}%" do
        (1..5).map{fa_icon "star"}.join.html_safe
      end
    bg = content_tag 'div', class: 'rating-star-bg' do
        (1..5).map{fa_icon "star"}.join.html_safe
      end
    content_tag 'div', class: 'rating-star' do
      [fg, bg].join.html_safe
    end.html_safe
  end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/bios/index.html.erb
<div class="hero text-center"></div><br />
	<div class="index_content">
  			<h2 class="awesome">Awesome People are Hard To Find</h2>
  			<p class="flex-box-fun">Let's Name Them</p>

   <!-- Button trigger modal -->
  <button type="button" class="btn btn-info btn-lg btn3d" data-toggle="modal" data-target="#exampleModal">
   Add a Cool Person
  </button>
  </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Vitals</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  <%= simple_form_for Bio.new, :html => {:multipart => true} do |f| %>
  <div class="modal-body col-xs-10 col-xs-offset-1">
    
      <%= f.input :name, placeholder: "Enter Your Name" %>
      <%= f.input :description, placeholder: "Describe Yourself" %>
      <%= f.input :hometown, placeholder: "Where you from?" %> 
      <%= f.input :caption, placeholder: "Add a caption" %> 
      <%= f.file_field  :picture  %><br />

      <br />

       <h5 class="modal-title" id="exampleModalLabel">Characteristics</h5>
  <div class="container">
    <div class="row">

      <span class="ratings">
            <div class="attribute"> 
                <div id="rating-form">
                   <span class="line-of-stars"><label class="text-left"><strong>Strength</strong></label></span>
                </div>
            </div>

       
            <div class="attribute">
              <div id="ratings-form">
                   <span class="line-of-stars"><label class="text-left"><strong>Endurance</strong></label></span>
                </div>
            </div><br />

        
             <div class="attribute">
             <div id="rate-form">
                   <span class="line-of-stars"><label class="text-left"><strong>Integrity</strong></label></span>
                </div>
             </div>
        
            <div class="attribute">
              <div id="star-form">
                   <span class="line-of-stars"><label class="text-left"><strong>Patience</strong></label></span>
                </div>
            </div><br />
          
            <div class="attribute">
              <div id="starring-form">
                   <span class="line-of-stars"><label class="text-left"><strong>Empathy</strong></label></span>
                </div>
            </div>
      </span>
    </div>
  </div>
</div>
  <%= f.submit 'Add a Cool Person', class: 'btn btn-info btn-lg btn3d' %> 
      
       
</div>


   
     
    </div>
  </div>
</div>
</div>

<% end %> 

<script>

  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'bio[rating]'
  });
</script>

<script>

  $('#starring-form').raty({
    path: '/assets/',
    scoreName: 'bio[rating]'
  });
</script>

<script>

  $('#rate-form').raty({
    path: '/assets/',
    scoreName: 'bio[rating]'
  });
</script>

<script>

  $('#star-form').raty({
    path: '/assets/',
    scoreName: 'bio[rating]'
  });
</script>

<script>

  $('#ratings-form').raty({
    path: '/assets/',
    scoreName: 'bio[rating]'
  });
</script>



    


    
<br />

<h1 class="title text-center ">The Awesome Ones</h1>
 
<div class="container">
  <div class="row text-center">
  <% @bios.each do |bio| %>
    <div class="booyah-box col-md-4">
      <p><%= image_tag bio.picture.to_s, :class => "picture" %></p> 
      <div class="details col-md-4">
        <h1><%= link_to bio.name, bio_path(bio), :class => "name" %></h1>
        <p class="caption"> <%= bio.caption %> </p>
      </div>
    </div> 
    <% end %>
  </div>
</div>

<div class="text-center">
  <ul class="pagination">
    <%= will_paginate @bios, renderer: BootstrapPagination::Rails, previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window: 0 %> </p>
  </ul>
</div>

app/views/bios/new.html.erb
<div class="new-hero col-xs-6 col-xs-offset-1" %> 
<h1> Add a Cool Person </h1>

<%= simple_form_for (@bio), :html => {:multipart => true} do |f| %>
		<%= f.input :name, placeholder: "Enter Your Name" %>
		<%= f.input :age, placeholder: "What's Your Age?" %>
		<%= f.input :description, placeholder: "Describe Yourself" %>
		<%= f.input :hometown, placeholder: "Where you from?" %> 
		<%= f.input :hobbies, placeholder: "What are your hobbies?" %> 
		<%= f.file_field  :picture  %><br />
		<br />
		<%= f.input :caption, placeholder: "Describe Your Photo" %>
		
<%= f.submit 'Add a person', class: 'btn btn-info btn-lg btn3d', :onclick => "alert('Are you sure this is correct?')" %> 

</div>

<% end %> 

app/views/bios/show.html.erb
	
	
	<div class="show-box col-xs-10 col-xs-offset-1">
		<div class="name-position">
			<p><%= image_tag(@bio.picture_url.to_s, class: 'show-page-pic') %></p>
			<h3 class="hero-name"><%= @bio.name %></h3>
		</div>
		
		<br />
		<div class="container">
					<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Click To Learn More</button>
  				<div id="demo" class="collapse">
  				<div class="details-show">
					
					<p><%= @bio.description %></p> 
					<p><%= @bio.hometown %></p> 
					
				</div>
				<div class="review-rating" data-score="<%= @bio.rating %>">
					<p class="col-3">Strength</p>
              		<%= @bio.strength %>
            	</div>
            	<div class="review-rating" data-score="<%= @bio.rating %>">
            		<p class="col-3">Endurance</p>
              		<%= @bio.endurance %>
            	</div>
            	<div class="review-rating" data-score="<%= @bio.rating %>">
            		<p class="col-3">Integrity</p>
              		<%= @bio.integrity %>
            	</div>
            	<div class="review-rating" data-score="<%= @bio.rating %>">
            		<p class="col-3">Patience</p>
              		<%= @bio.patience %>
            	</div>
            	<div class="review-rating" data-score="<%= @bio.rating %>">
            		<p class="col-3">Empathy</p>
              		<%= @bio.empathy %>
            	</div>

         <div class="col-xs-10 col-xs-offset-1">
             <%= simple_form_for @comment, url: bio_comments_path(@bio) do |f| %><br />
               <%= f.input :message, placeholder: "Add a message here", label: false  %> 
               <%= f.submit "Add Comment", class: 'btn btn-primary' %>
             <% end %> <br />
         
            <div class="comment-display">
              <h1 class="comment-h1">Here's What People Have Said</h1>
              <% @bio.comments.each do |comment| %>
                <blockquote>
                   <div class="new-comment">
                        <%= comment.message %> 
                   </div>
                </blockquote>
                <% end %>
                <button type="button" class="btn btn-primary">
                  <p>Contact Me</p>
                </button>
            </div>
        </div>
			</div>
		</div>

    


<script>
$('.review-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });

  </script>


<script>


  


	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bios</title>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="all">
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.filestyle/1.1.0/js/bootstrap-filestyle.min.js"> </script>
  </head>

  <body>
  <div id="flex-container">
    <nav class="navbar navbar-custom" role="navigation"> 
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
      </button>
      
      <%= link_to 'Hero App', root_path, class: 'navbar-brand' %>
      <%= link_to 'Hero Stories', stories_path, class: 'stories' %>
      </div>
<i class="glyphicon glyphicon-plus-sign"></i>
    <!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="navbar-nav mr-auto">
    <li>
      
      
      
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    
  </ul>
</div><!-- /.navbar-collapse -->
</nav>

<% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>

      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

    <%= yield %>

    </div>

    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-3">
        <b>Contact Info</b>
        <br />
        youngerik26@gmail.com
        <br />
        3628 Shaffer Rd
        <br />
         Rock Creek, Ohio, 44084
      </div>
    </div>
  </div>
</div>


  </body>
</html>

app/views/stories/index.html.erb
Boom